import '@/app/ui/globals.css';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ChatsProvider } from './lib/context/chatContext';
import { UserProvider } from './lib/context/userContext';
import { WebSocketProvider } from './lib/context/webSocketContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased text-gray-400`}
      >
        <UserProvider>
          <ChatsProvider>
            <WebSocketProvider>
              {children}
            </WebSocketProvider>
          </ChatsProvider>
        </UserProvider>
      </body>
    </html>
  );
}